### ISSUE TITLE
./pleasew build throws error

### ISSUE THREAD

**Issue by northdpole** [thought-machine/dracon#3]
## Issue
Cannot build project

### Expected behaviour
./pleasew build should build the project and generate an executable somewhere

### Actual behaviour

` [dracon master*]$ ./pleasew build
Build stopped after 1m23.57s. 1 target failed:
    //pkg/enrichment:enrichment
Error building target //pkg/enrichment:enrichment: exit status 1
pkg/enrichment/issue.go, line 54, column 5: undefined: errors.Is

`

### Steps to reproduce
On the latest master try building the project

**Comment by VJftw** [comment]
This is because your Go version is below 1.13 (which introduced `errors.Is` https://blog.golang.org/go1.13-errors). AFAIK Please doesn't have a way of restricting to a Go version, unfortunately.
