### ISSUE TITLE
Installation script fails to cUrl

### ISSUE THREAD

**Issue by northdpole** [thought-machine/dracon#4]
## Issue
Installation script fails to download the project producing the following error message:

`
$ bash <(curl -s https://raw.githubusercontent.com/thought-machine/dracon/master/scripts/install.sh)
-> determined linux OS
-> installing under /home/<user>/.local/bin
-> downloading  to /home/<user>/.local/bin/dracon
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
chmod: cannot access '/home/<user>/.local/bin/dracon': No such file or directory

-> You need to add /home/<user>/.local/bin to your PATH variable. e.g. export PATH=/home/<user>/.local/bin:$PATH;

/proc/self/fd/11: line 33: dracon: command not found
`
### Expected behaviour
~/.local/bin/ contains the dracon executable

### Actual behaviour
~/.local/bin/ is empty
### Steps to reproduce
follow the installation instructions

**Comment by northdpole** [comment]
further investigation:

`
curl -s https://api.github.com/repos/thought-machine/dracon/releases/latest
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3/repos/releases/#get-the-latest-release"
}

`

**Comment by steakunderscore** [comment]
This looks like the releases were not copied over when we opensourced the project.
