### ISSUE TITLE
Dracon installation not working properly on Microk8s

### ISSUE THREAD

**Issue by ValentineDragan** [thought-machine/dracon#43]
## Issue
I am following the [Getting Started guide](https://github.com/thought-machine/dracon/blob/master/docs/getting-started/minikube.md) to install Dracon on my local machine with Microk8s (and replacing `--context minikube` with `--context microk8s`).
Two of the pods (`dracon-enrichment-db` and `elasticsearch`) never start up and remain in the 'Pending' state with the following message
```
kubectl -n dracon-public describe pod elasticsearch-0
...
...
Events:
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Warning  FailedScheduling  11s (x1470 over 36h)  default-scheduler  pod has unbound immediate PersistentVolumeClaims
```

Following a recent debugging session with @northdpole , we managed to fix the issue for `dracon-enrichment-db` by going into `/resources/persistence/enricher-db/k8s.yaml` and updating the storageClassName to: `storageClassName: "fast-encrypted"`. Doing this change and restarting the deployment worked for the enricher, but not for elasticsearch.

### Expected behaviour
After following the installation instructions (with modifications for Microk8s), the four pods should be running correctly.

### Actual behaviour
Even after replacing `--context minikube` with `--context microk8s` and updating `storageClassName: "fast-encrypted"` to enricher-db/k8s.yaml and /elasticsearch-kibana/elasticsearch.yaml, one of the pods is still not starting properly:
```
$ kubectl -n dracon-public get pods
NAME                                READY   STATUS    RESTARTS   AGE
dracon-enrichment-db-0              1/1     Running   0          37h
elasticsearch-0                     0/1     Pending   0          37h
kibana-deployment-587b88548-7sdbh   1/1     Running   0          37h
minio-6d59bcc87c-jkzbn              1/1     Running   0          37h
```
With the elasticsearch pod showing the following error:
`Warning  FailedScheduling  11s (x1470 over 36h)  default-scheduler  pod has unbound immediate PersistentVolumeClaims`

### Steps to reproduce
1. Follow the Getting Started guide instructions, replacing the context with microk8s
```
$ kubectl --context microk8s apply --filename https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.9.0/release.yaml
$ kubectl --context microk8s create namespace dracon
$ kubectl apply --context microk8s --namespace dracon -f resources/persistence/enricher-db/k8s.yaml
$ kubectl apply --context microk8s --namespace dracon -f resources/persistence/elasticsearch-kibana/elasticsearch.yaml
$ kubectl apply --context microk8s --namespace dracon -f resources/persistence/elasticsearch-kibana/kibana.yaml
```
2. `$ kubectl --context microk8s -n dracon get pods` to see the pods. Two of them (enricher and elasticsearch) should be Pending forever.
3. Apply the changes mentioned above to get the enricher pod to work, but elasticsearch will still remain Pending.

**Comment by xavigpich** [comment]
Have you reproduced `minikube addons enable efk` somehow in microk8s? How many GBs of heap memory have you allocated on your microk8s environment?

**Comment by northdpole** [comment]
this is very old and has been resolved, i think
